### ISSUE TITLE
Hidden settings appear but hidden values are not displayed.

### ISSUE THREAD

**Issue by FNNN98** [amitxv/SCEWIN#1]
![image](https://github.com/amitxv/SCEWIN/assets/49247414/bec34af2-0c19-4ec5-8727-49c026fe506b)

This is a quick comparison with BoringBoredom's UEFI Editor. Due to Capsule Bios limitations on my Gigabyte AB350 Gaming 3 it fails to flash modified bioses even with efiflash mod.

That being said **SCEWIN appear to override this behaviour but it's not possible to input different values from the ones pre-existing in the .txt.**

For example:

Options	=[00]Auto	// Move "*" to the desired Option
         [01]Gen1
         [02]Gen2
         *[03]Gen3
         [**04]Gen4**

As described by Import.bat, it does not write over this part of code because Gen4 is not visible in this tool.

Context: B350/X370 artificial PCIE bus limitations. A bios with PCIe 4.0 support was released in 2019 but it was soon removed. 
Multiple settings such as PCIe Ten Tag Support which does only apply to PCIe 4.0 seem to point towards a still-existing PCIe 4.0 microcode support but this is intentionally disabled as a means of planned obsolescence and product segmentation.

**Comment by amitxv** [comment]
Just to be sure, does the BIOS file that you used for UEFI Editor match the one that is currently flashed?

**Comment by FNNN98** [comment]
Yes, it's the exact same bios (Bios version F52i for the GA-AB350-Gaming 3).

**Comment by amitxv** [comment]
Are there any duplicates of that setting in the text file? Honestly not sure. I don't actually use SCEWIN as it has some flaws.

**Comment by FNNN98** [comment]
I don't see any duplicate. My GPU is a 3080FE (which is paired with a 5800x3d).

I actually just used grub to force Gen4 and now the asterisk for the PCIE gen in PCIEX Slot Configuration disappeared because it's forcing a settings that doesn't exist in BIOSSettings.txt.

**Comment by kelemenabel** [comment]
When forcing *Gen4* via GRUB, what does GPU-Z report? - Is it actually reporting *Gen4*? (attach picture if possible)

And could you please paste this command:
``SCEWIN_64.exe /O /S nvram.txt /h HII.db 2> log_file.txt``
-- also attach the generated files please

**Comment by FNNN98** [comment]
It appears to max out at Gen3 but it still report Gen
![image](https://github.com/amitxv/SCEWIN/assets/49247414/fddc9ede-c265-424a-a691-12efb5d44c4c)
But for example CPU-Z appears to describe bus specs as 16GT/s.
![image](https://github.com/amitxv/SCEWIN/assets/49247414/e6202142-1298-4104-86a4-366641baf8a2)

The only difference I noticed when forcing Gen4 is that PCIE speed now appears to be dynamic. It switches between Gen1->Gen2->Gen3 depending on the workload

[log_file.txt](https://github.com/amitxv/SCEWIN/files/12378147/log_file.txt)

[nvram.txt](https://github.com/amitxv/SCEWIN/file

[BIOSSettings.txt](https://github.com/amitxv/SCEWIN/files/12378151/BIOSSettings.txt)
s/12378150/nvram.txt)

**Comment by kelemenabel** [comment]
> It appears to max out at Gen3.
Yeah, this is the expexted behaviour: Gigabyte (and also other vendors) were [forced to remove PCIe Gen4 support](https://www.guru3d.com/news-story/gigabyte-removes-pcie-4-support-on-all-amd-motherboards-that-are-not-x570.html) with AGESA updates.

> But for example CPU-Z appears to describe bus specs as 16GT/s
Probably because you forced *Gen4* via GRUB, and CPU-Z reads the value wrong --> misreports
Was the screenshot taken during GPU-Z's stress test? - because the current link speed is *8.0 GT/s* which is the limit of PCIe Gen3 -- this suggests that it's actually running on *Gen3* (which was already determined with GPU-Z, just for clarification)

> The only difference I noticed when forcing Gen4 is that PCIE speed now appears to be dynamic. It switches between Gen1->Gen2->Gen3 depending on the workload
This should be the case for all options. The "dynamic" behaviour you describe is a power-saving feature which is why GPU-Z's internal stress-test is needed to determine the actual PCIe specs

Thanks for the attached files, but the most important one was left out. Could you please also attach "*HII.db*?

**Comment by FNNN98** [comment]
Sure.
I had to use Mediafire because I can't upload .db file format on Github.
https://www.mediafire.com/file/wxmasqkq8t3wkgi/HII.db/file
