### ISSUE TITLE
amisce msi z690a pro d4

### ISSUE THREAD

**Issue by drwrdivol** [amitxv/SCEWIN#2]
### Motherboard model

msi z690 a pro d4

### Version

ver 5.03.1115

### Command type

please help me use the amisce bios editor for the msi z690 a pro dd4 motherboard, I really need to edit the bios, have you found a solution for msi motherboards? if it is possible to do this in some other way, then please help

### Log file

![Без имени](https://github.com/user-attachments/assets/80cbef83-9be5-4f26-849a-c25bda476e6b)

**Comment by ab3lkaizen** [comment]
Did you use `DL_SCEWIN.exe` from [here](https://github.com/ab3lkaizen/SCEHUB/releases/latest)? If so, a `log-file.txt` should have been generated after running `Export.bat`, containing the error message(s). From there, you *should* find the solution for your error in the [README](https://github.com/ab3lkaizen/SCEHUB/blob/main/README.md). If not, please upload `log-file.txt` instead of the picture, and provide the command used in the appropriate field.

**Comment by drwrdivol** [comment]
thx VERY MUCH!!!!02.08.2024, 11:55, "Abel" ***@***.***>:
Did you use DL_SCEWIN.exe from here. If so, a log-file.txt should have been generated after running Export.bat, containing the error message(s). From there, you should find the solution for your error in the README. If not, please upload log-file.txt instead of the picture, and provide the command used in the appropriate field.
